module.exports = {
  root: true,
  env: {
    es6: true,
    node: true,
    jest: true,
    es2021: true,
  },
  extends: [
    'airbnb-base',
    'eslint-config-prettier',
    'eslint:recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'prettier',
  ],
  parserOptions: {
    ecmaFeatures: {
      modules: true,
    },
    ecmaVersion: 12,
    sourceType: 'module',
  },
  plugins: ['prettier'],
  ignorePatterns: ['**/*.test.*'],
  rules: {
    'array-callback-return': 'error',
    'arrow-body-style': ['error', 'as-needed'],
    'comma-dangle': 'off',
    'consistent-return': 'off',
    'default-case': 'error',
    eqeqeq: [2, 'smart'],
    'import/default': 'error',
    'import/export': 'error',
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
    'import/first': 'error',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/no-extraneous-dependencies': 'off',
    'import/no-named-as-default': 'warn',
    'import/no-unresolved': [
      2,
      {
        commonjs: true,
        amd: true,
      },
    ],
    'import/no-unused-modules': 'off',
    'import/order': [
      'error',
      {
        pathGroups: [{ pattern: '@/**', group: 'parent', position: 'before' }],
      },
    ],
    'import/prefer-default-export': 'off',
    indent: 'off',
    'linebreak-style': ['error', 'unix'],
    'max-len': [
      'warn',
      {
        code: 120,
        ignoreComments: true,
        ignoreTrailingComments: true,
        ignoreUrls: true,
        ignorePattern: 'd="([\\s\\S]*?)"',
      },
    ],
    'no-console': 'off',
    'no-empty-function': 'off',
    'no-mixed-spaces-and-tabs': 'warn',
    'no-param-reassign': [
      'warn',
      {
        props: false,
      },
    ],
    'no-plusplus': 'warn',
    'no-self-compare': 'error',
    'no-shadow': 'off',
    'no-template-curly-in-string': 'warn',
    'no-underscore-dangle': 'warn',
    'no-unused-vars': 'warn',
    'no-use-before-define': 'off',
    'no-useless-concat': 'error',
    'no-var': 'error',
    'object-shorthand': 'warn',
    'prefer-arrow-callback': [
      'error',
      {
        allowNamedFunctions: true,
      },
    ],
    'prefer-const': 'error',
    'prefer-destructuring': [
      'error',
      {
        array: true,
        object: true,
      },
      {
        enforceForRenamedProperties: false,
      },
    ],
    'prettier/prettier': 'off',
    quotes: ['error', 'single'],
    radix: 'off',
    'require-await': 'error',
    semi: [1, 'always'],
    'valid-typeof': 'error',
  },
};
